### ISSUE TITLE
Embroider doesn't change all `{{rootURL}}` usage in index.html

### ISSUE THREAD

**Issue by evoactivity** [jelhan/webpack-subresource-integrity-embroider#11]
It seems embroider only updates the `rootURL` to the `publicPath` for files it processes from index.html (css and js).

I'm reporting this here because it causes a breakage in a production build when using this plugin and I'm wondering if you have any thoughts on how to proceed given this might not be fixed for a while on the embroider side. I thought fingerprinting would update those files, but apparently not.

Do you know of a safe way of determining the rootURL defined in the `environment.js` file from the webpack plugin? My initial thought would be to import `environment.js` from the established location and just pull it from there. We can then use regex to remove either `publicPath` or `rootURL` instead of just removing `publicPath`.

Tracking on embroider side https://github.com/embroider-build/embroider/issues/1767

**Comment by jelhan** [comment]
Could you please share steps to reproduce? That would be helpful.

**Comment by evoactivity** [comment]
1) Set a rootURL in your `environment.js`
2) Set `fingerprint.prepend` and embrdoider `publicAssetsURL` in `ember-cli-build.js` using a function like

```js
function isProduction() {
  return EmberApp.env() === 'production';
}

function getPublicAssetsUrl() {
  if (isProduction())  return 'https://a-cdn-url.com/admin/';
  return '/admin/';
}
```
3) Add favicons to index.html eg

```hbs
<link rel="apple-touch-icon" sizes="180x180" href="{{rootURL}}apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="{{rootURL}}favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="{{rootURL}}favicon-16x16.png">
<link rel="manifest" href="{{rootURL}}site.webmanifest">
<link rel="mask-icon" href="{{rootURL}}safari-pinned-tab.svg" color="#59298d">
```

I use RealFaviconGenerator, this should be available to download for demo https://realfavicongenerator.net/favicon_result?file_id=e84321826402102b84e9b9b52f14e1398051aefd

If not generate the favicon using their demo button.

4) Enable this plugin

5) Run a production build

**Comment by jelhan** [comment]
What is the result? Does the build fail? Or are you missing `integrity` attributes, which should be added?

**Comment by evoactivity** [comment]
Build fails, the rootURL fix we landed yesterday is using the webpack `publicPath` value to strip it from the asset locations, but because the favicons are using the rootURL from `environment.js` instead of the `publicAssetsURL` from `ember-cli-build.js` it is not removed and those files cannot be found on the file system. Only the CSS and JS files that use `{{rootURL}}` end up using the `publicAssetsURL` from embroider.

As I say, this is an embroider bug but we'll need to handle it until embroider is fixed and all `{{rootURL}}` usage in the index.html are the same.

**Comment by jelhan** [comment]
Do I understand correctly, that the primary issue is not the missing `integrity` attribute in this case but that the assets are not served from the configured CDN URL? So even if we land a workaround here, it wouldn't help affected apps much?

**Comment by evoactivity** [comment]
No, the build fails entirely, similar to what we solved in https://github.com/jelhan/webpack-subresource-integrity-embroider/issues/4. When this plugin tries to lookup the file on the filesystem it has the wrong path as it's using the wrong `{{rootURL}}` value as embroider seemingly ignores any link tags in `index.html` that are not css files.

So lets say I am running an app on https://domain.com/admin/, so I set the rootURL property in `environment.js` to `/admin/` as ember needs to know all routes will look like https://domain.com/admin/some/route/1, so rootURL in `environment.js` should always be `/admin/`, it should never change regardless of environment.

The embroider/webpack option `publicAssetsURL` is being used to prepend the asset urls like the older `fingerprint.prepend` option would do in a classic build, in my production build I have this set to `https://my-cdn.com/`.

eg 

```hbs
{{! this rootURL is replaced with publicAssetsURL from embroider }}
<link integrity="" rel="stylesheet" href="{{rootURL}}assets/vendor.css">
{{! so it becomes }}
<link integrity="" rel="stylesheet" href="https://my-cdn.com/assets/vendor.f37def1f2e1fb65adb6312e13fea69ac.css">

{{! but this rootURL is replaced with rootURL from environment.js }}
<link rel="apple-touch-icon" sizes="180x180" href="{{rootURL}}apple-touch-icon.png">
{{! and becomes }}
<link rel="apple-touch-icon" sizes="180x180" href="/admin/apple-touch-icon.png">
```

The way we replace this in the build, to find the file on the filesystem, is to use `publicPath` as supplied by webpack, which is the value we set `publicAssetsURL` to. So when we loop over the asset locations we are looking for `https://my-cdn.com/` and replacing it with '/', but because the favicons are in the html as `/admin/apple-touch-icon.png` this replacement fails and we try to read the file at `/var/folders/rw/zh799lvx7lzb46z1mh_r851m0000gn/T/broccoli-27890EVXZIM2sCKQ2/out-1227-packager_runner_embroider_webpack/admin/apple-touch-icon.png` but that admin folder doesn't exist.

I'll create a reproduction repo later or tomorrow morning.

**Comment by evoactivity** [comment]
I might have a go at fixing this in embroider before we do anything here. Hopefully I can get something landed asap and this won't be a problem here.

**Comment by evoactivity** [comment]
Well, I don't think they're going to accept a PR from me. They're planning on making index.html a true entrypoint for next major, which will probably make the usage of this addon redundant anyway.

https://github.com/embroider-build/embroider/issues/1767#issuecomment-1952186219

So I guess we will need to add a workaround anyway :(

**Comment by jelhan** [comment]
> So I guess we will need to add a workaround :(

My recommendation would be a Webpack plugin similar to this one, which adds the `publicAssetsURL` to those assets missing it. As long as it runs before webpack-subresource-integrity-embroider, everything should work afterwards as expected.

**Comment by evoactivity** [comment]
Ok well, I have a fix working. It's small and simple.

1) Get the environment from the index.html
```js
const environmentMeta = indexHtml.window.document.querySelector('meta[name$="/config/environment"]');
const { rootURL } = JSON.parse(indexHtml.window.unescape(environmentMeta.getAttribute('content')));
```

2) Update the replace like this
```js
const fileName = assetLocation.replace(new RegExp(`^(${publicPath}|${rootURL})`), "/");
```

**Comment by jelhan** [comment]
Would that be helpful for your use case? The URL for those assets will be still wrong. Even though they would have correct `integrity` and `crossorigin` attributes.

**Comment by evoactivity** [comment]
Yes, I have been dealing with embroider not outputting the correct rootURL for those elements for a long time, I serve those favicons from the same url as the index.html so in my case, they are "correct", in so that they will resolve to a file and be served.

I'm more interested in making sure this plugin doesn't break builds that have this incorrect embroider behaviour present rather than fixing the root cause of that behaviour (though that would be nice it's not the responsibility of this plugin).

**Comment by jelhan** [comment]
I'm good with detecting the `rootURL` used by Ember CLI in addition to `publicAssetsURL` used by Embroider. Please feel free providing a PR with your solution to detect the `rootURL` described above.

**Comment by evoactivity** [comment]
I'll prepare a PR with a test case later on tonight after work.
