### ISSUE TITLE
<link> transformation is overeager on <link>s with a relationship that doesn't support applying `integrity`

### ISSUE THREAD

**Issue by meirish** [jelhan/webpack-subresource-integrity-embroider#15]
:wave: hello! Thanks for building this!

I was trying it out in our project and noticed it was complaining about some `<link rel="dns-prefetch">`, so I went to look at some documentation.

According to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link#integrity), `integrity` is only valid for a <link> if the `rel` attribute is one of "stylesheet", "module", or "modulepreload". 

Would you take a PR implementing that behavior for this plugin? I ask because I see some tests verifying that `integrity` gets applied on other link relationships - it's possible browsers _do_ check other things the information on MDN isn't correct, but I didn't verify.

**Comment by jelhan** [comment]
Good catch. A PR fixing it is very welcome.

> I ask because I see some tests verifying that `integrity` gets applied on other link relationships

Could you please provide an example?

**Comment by meirish** [comment]
I'm sure this isn't exhaustive, but the one I saw was verifying the hash on a `<link rel="manifest" />`. I'm working on it now and will see if tests surface other cases.

**Comment by jelhan** [comment]
> I'm sure this isn't exhaustive, but the one I saw was [verifying the hash on a `<link rel="manifest" />`](https://github.com/jelhan/webpack-subresource-integrity-embroider/blob/5b1def56b8de3bb2c10e520a222bb02c5e6d9cb6/tests/test.js#L85-L94).

Good catch. Those tests seems to be wrong. The same applies for the favicon tests.

I double checked in the HTML specification and integrity attribute is not supported for those:

> The integrity attribute represents the [integrity metadata](https://fetch.spec.whatwg.org/#concept-request-integrity-metadata) for requests which this element is responsible for. The value is text. The attribute must only be specified on [link](https://html.spec.whatwg.org/multipage/semantics.html#the-link-element) elements that have a [rel](https://html.spec.whatwg.org/multipage/semantics.html#attr-link-rel) attribute that contains the [stylesheet](https://html.spec.whatwg.org/multipage/links.html#link-type-stylesheet), [preload](https://html.spec.whatwg.org/multipage/links.html#link-type-preload), or [modulepreload](https://html.spec.whatwg.org/multipage/links.html#link-type-modulepreload) keyword. [[SRI]](https://html.spec.whatwg.org/multipage/references.html#refsSRI)
>
> https://html.spec.whatwg.org/multipage/semantics.html#attr-link-integrity

I think we want to make sure that the attribute is only added on `<link>` if `rel` contains at least one of `stylesheet`, `preload`, or `modulepreload`.
